version: '3.8'

services:
  postgres-sistema:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ms-sistema-db
    ports:
      - "5436:5432"
    volumes:
      - postgres_sistema_data:/var/lib/postgresql/data
    networks:
      - saude-network

  postgres-cliente:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ms-cliente-db
    ports:
      - "5435:5432"
    volumes:
      - postgres_cliente_data:/var/lib/postgresql/data
    networks:
      - saude-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - saude-network

networks:
  saude-network:

volumes:
  postgres_sistema_data:
  postgres_cliente_data:
